Feature/documentation field
osulp/Scholars-Archive pull request #2278
Opened 2021-07-19 15:44 UTC by straleyb

Adds in documentation field, indexes and presents it to admin.

2021-07-19 15:45 UTC, straleyb commented
<img width="1482" alt="Screen Shot 2021-07-19 at 8 44 24 AM" src="https://user-images.githubusercontent.com/6424683/126188294-989edc95-7f96-4d8a-abae-8d7f6ce7802f.png">
<img width="1229" alt="Screen Shot 2021-07-19 at 8 44 56 AM" src="https://user-images.githubusercontent.com/6424683/126188304-9dc81ac9-b115-4a8a-963e-beda61ccbc8d.png">

2021-07-19 23:00 UTC, CGillen requested changes

2021-07-19 23:00 UTC, CGillen commented on app/indexers/default_work_indexer.rb
> +      solr_doc['documentation_ssim'] = object.documentation
Doesn't `index.as :stored_searchable` automatically index `documentation_tesim`?

2021-07-19 23:00 UTC, CGillen commented on app/models/solr_document.rb
> +
Which would make this redundant, since the `#solarized_methods` below already creates a method to access `documentation_tesim`

2021-07-20 16:55 UTC, CGillen approved these changes

2021-07-20 16:56 UTC, merged