Log customization (Progress)
osulp/Scholars-Archive pull request #2423
Opened 2022-11-18 23:32 UTC by lamtu1

Adding in the development of customizing the log output using Logger. Currently still in progress.

2022-11-18 23:34 UTC, lamtu1 commented
<img width="732" alt="Screenshot 2022-11-18 at 3 33 34 PM" src="https://user-images.githubusercontent.com/111306182/202820327-ee1015cf-f2ab-4e25-a515-5911c511ba94.png">

Progress so far using ```Logger``` on customization.

2022-11-23 18:35 UTC, lamtu1 commented
<img width="685" alt="Screenshot 2022-11-23 at 10 34 51 AM" src="https://user-images.githubusercontent.com/111306182/203622761-84a703b0-3f7b-4043-ba6c-244eefc1fd92.png">
New progress image of the log

2022-11-23 22:10 UTC, lamtu1 commented
<img width="716" alt="Screenshot 2022-11-23 at 2 10 17 PM" src="https://user-images.githubusercontent.com/111306182/203654439-15bf7490-0dc8-4a0b-9eca-68a06b75e767.png">
New screenshot with the color escape key remove.

2022-11-23 22:38 UTC, lamtu1 commented
<img width="686" alt="Screenshot 2022-11-23 at 2 35 19 PM" src="https://user-images.githubusercontent.com/111306182/203657429-9fa4ee31-22a2-417a-abaf-e834fdce5b1c.png">
Removing the bracket from the string field area of ```req_id``` & ```req_uri```

2022-11-30 22:44 UTC, CGillen requested changes

2022-11-30 22:44 UTC, CGillen commented on config/environment.rb
> +Rails.application.configure do
Tab => 2 space

2022-11-30 22:44 UTC, CGillen commented on config/environments/production.rb
> +  # config.log_formatter = ::Logger::Formatter.new
Just remove both line, no comments

2022-11-30 22:44 UTC, CGillen commented on config/environments/staging.rb
> +  # config.log_tags = [:request_id]
No comments

2022-11-30 22:44 UTC, CGillen commented on config/environments/staging.rb
> +  # config.log_formatter = ::Logger::Formatter.new
No comments

2022-11-30 22:44 UTC, CGillen commented on config/initializers/lograge.rb
> -    config.lograge.custom_options = lambda do |event|
Reset this file and open a new ticket for removing LogRage. In it ping Ryan O about if we're using any existing LR functionality

2022-12-01 20:57 UTC, CGillen approved these changes

2022-12-01 20:57 UTC, merged