Add in search filter with id
osulp/Scholars-Archive pull request #2527
Opened 2023-09-12 21:59 UTC by lamtu1

Create a new searching way of using the `GeoName ID` to search for the place without typing in the name.

2023-09-12 21:59 UTC, lamtu1 commented
fixes #1443

2023-09-13 16:21 UTC, lamtu1 commented
`DEMO:` VIdeo showing the ID number input works on the GeoName location

https://github.com/osulp/Scholars-Archive/assets/111306182/b9255315-a697-49b8-a32f-5f1c6cc5fa85

2023-09-18 16:55 UTC, lamtu1 commented
Ready for review/approve and merge for QA.

2023-09-19 16:21 UTC, CGillen requested changes

2023-09-19 16:21 UTC, CGillen commented on .rubocop_fix_me.yml
>      - 'lib/scholars_archive/validators/other_affiliation_validator.rb'
Could you fix these? They shouldn't be too difficult, maybe even auto-solvable (`rubocop -A`)

2023-09-20 18:33 UTC, CGillen requested changes
`Metrics/MethodLength` is fine. It's a problem generally everywhere

2023-09-20 18:33 UTC, CGillen commented on lib/qa/authorities/geonames.rb
> +        'label' => label.call(response, translate_fcl(response['fcl'])) }]
space here. that's `Layout/HashAlignment`

2023-09-20 18:33 UTC, CGillen commented on lib/qa/authorities/geonames.rb
> +      elsif q.to_s.match(%r{^https?:\/\/www\.geonames\.org})
I'm not sure what's different in OD2, but you don't need to escape the `//` part if the regex is in a `%r{}` block apparently
That's `Style/RedundantRegexpEscape`

2023-09-21 15:04 UTC, lamtu1 commented
@CGillen Got it all fixed, and ready for review

2023-09-21 21:12 UTC, merged