Add in error handling to locale
osulp/Scholars-Archive pull request #2528
Opened 2023-09-14 16:43 UTC by lamtu1

Add in a way to handle the param for locale and not raise the `I18n::InvalidLocale`.

2023-09-14 16:45 UTC, lamtu1 commented
`DEMO:` Showcasing the error handling of locale.

https://github.com/osulp/Scholars-Archive/assets/111306182/6df46475-f1b0-441d-82df-d044a7b4471f

2023-09-14 16:45 UTC, lamtu1 commented
fixes #1880

2023-09-18 16:55 UTC, lamtu1 commented
Ready for review/approve and merge for QA.

2023-09-19 16:12 UTC, CGillen requested changes

2023-09-19 16:12 UTC, CGillen commented on app/controllers/concerns/hyrax/controller.rb
> +module Hyrax::Controller
See that this is a module & not a class. We should be able to find where this is imported and override the method there without pulling in this whole module

2023-09-19 16:12 UTC, CGillen commented on app/controllers/concerns/hyrax/controller.rb
> +module Hyrax::Controller
https://github.com/osulp/Scholars-Archive/blob/main/app/controllers/application_controller.rb#L12

2023-09-20 18:34 UTC, CGillen approved these changes

2023-09-20 18:34 UTC, merged